# Generated by Django 5.0 on 2026-10-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_footwear_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='holiday_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='season',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
