# Generated by Django 5.0 on 2026-10-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_product_id'),
        ('sales', '0003_alter_sale_holiday_name_alter_sale_season'),
        ('shops', '0003_alter_shop_shop_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['shop', 'product', 'date'], name='sales_sale_shop_id_e779ad_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['date'], name='sales_sale_date_ca4177_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['shop'], name='sales_sale_shop_id_351c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['product'], name='sales_sale_product_d1188a_idx'),
        ),
    ]
